spring.application.name=spotifyclient
spring.config.import=optional:file:local.env[.properties]

# Spotify API Configuration
spotify.client-id=${SPOTIFY_CLIENT_ID}
spotify.client-secret=${SPOTIFY_CLIENT_SECRET}
